//Post http://localhost:3000/api/users
//updating user with id=35
//PATCH  http://localhost:3000/api/users/35
//DELETE http://localhost:3000/api/users/35
//Post http://localhost:3000/api/users
Post http://localhost:3000/api/users

Content-Type: application/json

{
  "username": "tomiii",
  "password": "000pass123",
  "total_score": 88
}
//{
//  "total_score": 100
//}
